2024-05-23 21:42:02.187 Uncaught app exception
Traceback (most recent call last):
  File "/Users/yanjunk/ballantyne-pyscripts/venv/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 600, in _run_script
    exec(code, module.__dict__)
  File "/Users/yanjunk/ballantyne-pyscripts/xirr/gui.py", line 14, in <module>
    res_data_frame, interim = main_func(cashflow, monthend, starting, return_iterim=True)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: main_func() got an unexpected keyword argument 'return_iterim'
